//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcioStoreIngSoftII.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OcioStoreIngSoftII.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BibliotecaJuegos_1 {
            get {
                object obj = ResourceManager.GetObject("BibliotecaJuegos 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox {
            get {
                object obj = ResourceManager.GetObject("checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_button {
            get {
                object obj = ResourceManager.GetObject("delete_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disk_solid_full {
            get {
                object obj = ResourceManager.GetObject("floppy-disk-solid-full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaCompra {
            get {
                return ResourceManager.GetString("PlantillaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaEstadística {
            get {
                return ResourceManager.GetString("PlantillaEstadística", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaReserva {
            get {
                return ResourceManager.GetString("PlantillaReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        table {
        ///            border-spacing: 0;
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        /* ================= HEADER ================= */
        ///        .header-table {
        ///            width: 100%;
        ///            border: 0;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///         [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string PlantillaVenta {
            get {
                return ResourceManager.GetString("PlantillaVenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printer_icon {
            get {
                object obj = ResourceManager.GetObject("printer_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
