//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcioStoreIngSoftII.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OcioStoreIngSoftII.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BibliotecaJuegos_1 {
            get {
                object obj = ResourceManager.GetObject("BibliotecaJuegos 1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkbox {
            get {
                object obj = ResourceManager.GetObject("checkbox", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete_button {
            get {
                object obj = ResourceManager.GetObject("delete_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap floppy_disk_solid_full {
            get {
                object obj = ResourceManager.GetObject("floppy-disk-solid-full", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlantillaCompra {
            get {
                return ResourceManager.GetString("PlantillaCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlantillaEstadística {
            get {
                return ResourceManager.GetString("PlantillaEstadística", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        .header-section {
        ///            display: flex;
        ///            justify-content: space-between;
        ///            align-items: flex-start;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///        .business-info {
        ///            text-align: center;
        ///            flex-grow: 1;
        ///        }
        ///
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlantillaReserva {
            get {
                return ResourceManager.GetString("PlantillaReserva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;OCIO STORE - DOCUMENTO GENERADO&lt;/title&gt;
        ///    &lt;style&gt;
        ///        body {
        ///            font-family: sans-serif;
        ///            color: #4a5568;
        ///            padding: 20px;
        ///        }
        ///
        ///        table {
        ///            border-spacing: 0;
        ///            border-collapse: collapse;
        ///        }
        ///
        ///        /* ================= HEADER ================= */
        ///        .header-table {
        ///            width: 100%;
        ///            border: 0;
        ///            margin-bottom: 25px;
        ///        }
        ///
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlantillaVenta {
            get {
                return ResourceManager.GetString("PlantillaVenta", resourceCulture);
            }
        }
    }
}
