//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OcioStoreIngSoftII.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OCIO STORE")]
        public string NombreNegocio {
            get {
                return ((string)(this["NombreNegocio"]));
            }
            set {
                this["NombreNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20-12345678-9")]
        public string CUITNegocio {
            get {
                return ((string)(this["CUITNegocio"]));
            }
            set {
                this["CUITNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Av. Siempre Viva 123")]
        public string DireccionNegocio {
            get {
                return ((string)(this["DireccionNegocio"]));
            }
            set {
                this["DireccionNegocio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=COMPUPROGJJM\\SQLEXPRESS;Initial Catalog=ocio_store;Integrated Securit" +
            "y=True;TrustServerCertificate=True")]
        public string cadena_conexion {
            get {
                return ((string)(this["cadena_conexion"]));
            }
            set {
                this["cadena_conexion"] = value;
            }
        }
    }
}
